# ===========================
# PROD Profile (Render.com)
# ===========================


spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# CORS - your deployed Vercel URL
cors.allowed-origin=${CORS_ORIGIN}

# Logging
logging.level.com.expensetracker=INFO
spring.jpa.show-sql=false
