
spring.datasource.url=jdbc:h2:file:./data/expensetrackerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false


# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# CORS
cors.allowed-origin=${CORS_ORIGIN}

# Logging
logging.level.com.expensetracker=INFO
